### ISSUE TITLE
Getting The Hash160 of the Public Key

### ISSUE THREAD

**Issue by sezginyildirim91** [albertobsd/keysubtracter#1]
Hello, I tried to understand the possibilities but not fully understood. Why should I provide public keys as input if it is extracting public keys within a certain range? I didn't understand him

Also, how can I output the hash160 of public keys? I want to check my hash160 address like this.

Thanks Alberto.

**Comment by albertobsd** [comment]
you use the publickeys directly with keyhunt `xpoint` mode it is faster than `rmd10` or `addres` mode, you can see the example in the keyhunt readme:

https://github.com/albertobsd/keyhunt#xpoint-mode

anyway i will paste here as a reference:

Example input file in keyhunt shorter version, the `tests/substracted40.txt` have more publickeys inside:

```
034eee474fe724cb631d19f24934e88016e4ef2aee80d086621d87d7f6066ff860 # - 453856235784
0274241b684e7c31e7933510b510aa14de9ac88ec3635bdd35a3bcf1d16da210be # + 453856235784
03abc6aff092b9a64bf69e00f4ec7a8b7ca51cfc6656732cbbc9f5674925b88609 # - 529328067324
034f4fe33b02c202b732d278f90eedc635af6f3be8a93c8d1cb0a01f6399aab2a4 # + 529328067324
03716ff57705e6446ac3e217c8c8bd9e9c8e58547457a6fe93ac254c37fd48afcb # - 14711740067
02ffa0769b0459c64b41f59f93495063ae031de0b846180bee37f921f20e141f60 # + 14711740067
03de1df5d801bbd5e7d86577bf14950f732fd41e586945d06d19e0fdea41a37d62 # - 549755814000
038d3711fd681e26c05b2f0cd423fa596e15054024e40add24a93bfa0c630531f1 # + 549755814000
03a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f0edbee53de0d4 # target
```

Example command line:

```
./keyhunt -m xpoint -f tests/substracted40.txt -n 65536 -t 4 -b 40
```

Example output:

```
[+] Version 0.1.20210330
[+] Setting mode xpoint
[+] Setting 4 threads
[+] Min range: 8000000000
[+] Max range: ffffffffff
[+] Opening file tests/substracted40.txt
[+] Allocating memory for 6003 elements: 0.11 MB
[+] Initializing bloom filter for 6003 elements.
[+] Loading data to the bloomfilter
[+] Bloomfilter completed
[+] Sorting data
[+] 6003 values were loaded and sorted
Thread 3 : Setting up base key: 0000000000000000000000000000000000000000000000000000008001d00000
Thread 0 : Setting up base key: 00000000000000000000000000000000000000000000000000000080025b0000
HIT!! PrivKey: 000000000000000000000000000000000000000000000000000000800258a2ce
pubkey: 0274241b684e7c31e7933510b510aa14de9ac88ec3635bdd35a3bcf1d16da210be
Thread 1 : Setting up base key: 0000000000000000000000000000000000000000000000000000008002910000^C
```

then you can calculate back the original privatekeys making some subtraction or addition.

Here is the comparation in metter of speed:

`xpoint` > `rmd10` > `address`

**Comment by sezginyildirim91** [comment]
I haven't tried Keyhunt xpoint before because I didn't understand. I ran a few tests today and finally got it. Great job and intelligence 🎉🎉🎉

**Comment by sezginyildirim91** [comment]
I would appreciate it if you could do that for RIPEMD160 as well.

**Comment by albertobsd** [comment]
Sorry but that is not possible, for publickeys we can do a lot of math with it, but with hashes rmd160 or base58 we can't do anything.
