### ISSUE TITLE
Does RIPEMD mode word only with HASH160 of pubkeys and not work with bitcoin addresses directly ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keysubtracter#10]
Does RIPEMD mode word only with HASH160 of pubkeys and not work with bitcoin addresses directly ?

Then I try use RIPEMD of addresses I get this:

[+] Sorting data ... done! 310497 values were loaded and sorted
Base key: fffffffffffffffffffffffff649cafe
Base key: fffffffffffffffffffffffffeaf5533      s
Base key: fffffffffffffffffffffffff6586bd5      /s
Base key: ffffffffffffffffffffffffff3bc381      /s
...
...
...
Base key: fffffffffffffffffffffffffacbd7cc      s/s
Base key: fffffffffffffffffffffffff7c72198      s/s
Base key: fffffffffffffffffffffffffd7c9d67      s/s
Base key: fffffffffffffffffffffffff36c7836      s/s

exit....

NOTHING FIND :( 

Br

**Comment by albertobsd** [comment]
In keyhunt each mode work diffent, if you are looking for address uses address mode, for rmd160 use rmd160 hashes, it work in that way beacuse at the beggining  of the development of the tool I add the "vanity" search mode -v 1MyAddress.... I need remove that option, and then convert addrress directly in hash rmd160.

and yes to your question:

> Does RIPEMD mode word only with HASH160 of pubkeys and not work with bitcoin addresses directly ?

Yes RMD160 only work with the double hash of those publickey. I already explain why.
