### ISSUE TITLE
Luis, make  please memory needs calculation ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keysubtracter#12]
Luis, good day.

Then I use subtracter and then use keyhunt, a lot of time is spent on reworking due to the fact that after I made the file and upload it to keyhant, it turns out that there is not enough RAM afterwards.

Screen https://ibb.co/BP5Vw4g

Can you make a check for how many memory will need then using a keyhunt and keysubtracter, and not make files what will be killed after because out of memory ?

I spend 80% time of work for this trouble.

Regars !

**Comment by albertobsd** [comment]
Sorry to hear that trouble, I don't know how much memory do you have but, but load 400 Million of publickeys is really a lot, the program use ~24 to ~ 28 bytes per item so 400 Millions of items may use some more than 10 GB of RAM

please make the calculations before to load so many items.

Regards!
