### ISSUE TITLE
How do you calculate the new keys?

### ISSUE THREAD

**Issue by greg2paris** [albertobsd/keysubtracter#19]
Hi alberto, Im very interesting in your keysubtracter, can you tell me how do you calculate the new keys?
Do you replace the Gx and Gy by the public key X and Y Values?
I kind of see how you can add keys but, how do you substract the keys from there?

**Comment by albertobsd** [comment]
Subtract and addition is the same operation, that is made with any method that performed Point Addition.

Let to say that you have Publickey C, and you want add and subtract the amount of the publickey of 1000.

P(C)+P(1000) = new Publickey (C + 1000)
P(C) +P(-1000) = new Publickey (C - 1000)

In both cases the operation is Point Addition, but in one of them the value is the same (1000) but Negated (-1000)
You can search in google some examples of how to get the Negated Value of a ECC Point

This is a very vague explanation f fthe Operation, let me know if you want more help and i will add some technical stuff
 
Regards!

**Comment by greg2paris** [comment]
Thanks for the answer, I will search for Negated Value of a ECC Point as you suggested.
I think it would be great to add this explanation so it would help to understand the use of the program.
Great job for the program btw.

**Comment by greg2paris** [comment]
> Subtract and addition is the same operation, that is made with any method that performed Point Addition.
> 
> Let to say that you have Publickey C, and you want add and subtract the amount of the publickey of 1000.
> 
> P(C)+P(1000) = new Publickey (C + 1000) P(C) +P(-1000) = new Publickey (C - 1000)
> 
> In both cases the operation is Point Addition, but in one of them the value is the same (1000) but Negated (-1000) You can search in google some examples of how to get the Negated Value of a ECC Point
> 
> This is a very vague explanation f fthe Operation, let me know if you want more help and i will add some technical stuff
> 
> Regards!

I think i Got the basic idea, it looks like what we do if we want to verify a signature.
