### ISSUE TITLE
Calculation error

### ISSUE THREAD

**Issue by SUN-2913** [albertobsd/keysubtracter#21]
Hi, @albertobsd !
Please check, there may be an error in the calculations:

> 022b7c223794d0d938e28fa622975f267a6a3c10a2be73ca090d5b93782000b633 # - 1
> 03b2f16665122b6d52439d3ad8505e35810e05da5a334b3142cc4e207da002a963 # + 1
> 038b6e862a3556684850b6d4f439a2595047abf695c08b6414f95a13358dd553fd # target

038b6e862a3556684850b6d4f439a2595047abf695c08b6414f95a13358dd553fd = privatkey 800000000000000000000000000000
If you take **1 step back**, there should be a private key 7FFFFFFFFFFFFFFFFFFFFFFFFFFFFF with PubKey: 03B2F16665122B6D52439D3AD8505E35810E05DA5A334B3142CC4E207DA002A963
But the program specifies this PubKey as **step +1** Maybe I don't understand something, but so far I have decided that the program incorrectly puts the signs - +
Users can easily get confused.

**Comment by Gusev39rus** [comment]
Sorry, I get it. This is +1 step from the current pubKey to the target, not from the target to the current one.

**Comment by albertobsd** [comment]
> Sorry, I get it. This is +1 step from the current pubKey to the target, not from the target to the current one.

Exctly i need to clarify this, i will edit the README in the next update.

Regards!
