### ISSUE TITLE
-t Option

### ISSUE THREAD

**Issue by sezginyildirim91** [albertobsd/keysubtracter#22]
Hello Alberto,

Can you bring multi-core support?

Thank you.

**Comment by albertobsd** [comment]
I don't know bro, that option is too much work in code. Also since you can let it run for some day and dont use it again i dont see sense of the option.

What kind of task are you looking for?

**Comment by sezginyildirim91** [comment]
> I don't know bro, that option is too much work in code. Also since you can let it run for some day and dont use it again i dont see sense of the option.
> 
> What kind of task are you looking for?

I modified this software and I have a different idea.

In fact, it would be much more efficient if I could integrate it into the video card, but I do not have that level of software knowledge and it will take me many years to learn.

I want to share this idea with you via telegram.

**Comment by sezginyildirim91** [comment]
> I don't know bro, that option is too much work in code. Also since you can let it run for some day and dont use it again i dont see sense of the option.
> 
> What kind of task are you looking for?

https://github.com/sezginyildirim91/keysubtracter

You can understand why I want the -t' option here.
