### ISSUE TITLE
Subtraction

### ISSUE THREAD

**Issue by Delti42** [albertobsd/keysubtracter#24]
I would like to understand the principle of calculation by the program. What values it takes away to get another public key. And can public keys be added or subtracted from each other?

**Comment by albertobsd** [comment]
I open a discution thread talking about this

https://github.com/albertobsd/keyhunt/discussions/136

There i show some examples and there is one tool to do it manually by your self

**Comment by Delti42** [comment]
> I open a discussion thread talking about this
> 
> [albertobsd/keyhunt#136](https://github.com/albertobsd/keyhunt/discussions/136)
> 
> There i show some examples and there is one tool to do it manually by your self.
> 
> But yes they need to be publickeys to be subtracted each other

Have you ever worked with FPGA? Is it possible to consider the option of transferring public keys to the FPGA, so that the FPGA would do the processing of public keys in rmd160. This is for the low ranges of the puzzle.
