### ISSUE TITLE
Error with make

### ISSUE THREAD

**Issue by Knopius** [albertobsd/keysubtracter#25]
Hello!

I am trying to install the program, but it gives an error.
Please tell me how to fix it.

Thank you very much.

└─$ make
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c gmpecc.c -o gmpecc.o
gcc -O3 -c util.c -o util.o
gcc -o keysubtracter keysubtracter.c gmpecc.o util.o sha256.o base58.o rmd160.o -lgmp
/usr/bin/ld: gmpecc.o:(.bss+0x2020): multiple definition of `EC'; /tmp/ccLtRTfw.o:(.bss+0x0): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x0): multiple definition of `DoublingG'; /tmp/ccLtRTfw.o:(.bss+0x40): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x2000): multiple definition of `G'; /tmp/ccLtRTfw.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:7: default] Error 1

**Comment by we-akri** [comment]
I have the same problem

**Comment by Knopius** [comment]
how can this be solved ?

**Comment by Knopius** [comment]
gcc (Debian 10.3.0-11) 10.3.0 
Kali Release:        2021.3
libgmp-dev is already the newest version (2:6.2.1+dfsg-2)

**Comment by macsim26** [comment]
Hi 
you must install gcc 9 and choose it as alternative.

**Comment by Knopius** [comment]
How can I choose it as alternative ? Which command does it do ?

**Comment by Knopius** [comment]
> Hi you must install gcc 9 and choose it as alternative.

Haw can I install gcc 9? Help me, please.

**Comment by macsim26** [comment]
Hi follow this tutorial it works on all debian version:
https://linuxconfig.org/how-to-switch-between-multiple-gcc-and-g-compiler-versions-on-ubuntu-20-04-lts-focal-fossa
Cordfially.
Roberto

**Comment by Knopius** [comment]
sudo make
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c gmpecc.c -o gmpecc.o
gmpecc.c:1:10: fatal error: gmp.h: No such file or directory
    1 | #include <gmp.h>
      |          ^~~~~~~
compilation terminated.
make: *** [Makefile:5: default] Error 1

**Comment by Knopius** [comment]
apt install libgmp3-dev
And, make did It. ))
