### ISSUE TITLE
-n Range

### ISSUE THREAD

**Issue by sezginyildirim91** [albertobsd/keysubtracter#26]
Why not do it so that the subtracted range extends from 1 to FFFFFFFFFFFFF?

For example 1:FFFFFFFFFFFF

The size N subtracted within this range does not start from 1, but starts from a number close to (FFFFFFFFFFFF).

Can you do this starting from 1? Can't we logically increase the probability that way?

**Comment by albertobsd** [comment]
> Can't we logically increase the probability that way?

Any number of subtracted keys increase the possibility.

The program calculate the length of the range this is:
length = End range - start range
And the it make a division of Length between the number of N this is something like a segment or to be more exact this is the number to add and subtract from the target key so every key will be
target  + 1*length
target  - 1*length
target  + 2*length
target  - 2*length
target  + 3*length
target  - 3*length
...
target  + (N+1)*length
target  - (N-1)*length
