### ISSUE TITLE
sad, its not working in address or rmd160 mode. please fix this

### ISSUE THREAD

**Issue by anshukrsingh** [albertobsd/keysubtracter#29]
![Screenshot (183)](https://user-images.githubusercontent.com/80658595/169501318-c8f9397f-b271-4150-8e33-d9503db035cf.png)

**Comment by anshukrsingh** [comment]
-f address, -f rmd160 collides with other -f 1 0r -f 2 parameters

**Comment by anshukrsingh** [comment]
even -x , not working

**Comment by albertobsd** [comment]
It is working

![image](https://user-images.githubusercontent.com/17832765/169536647-48e121d7-b8df-4bea-87f6-9504430aaeef.png)

![image](https://user-images.githubusercontent.com/17832765/169536775-ecc30991-bab0-4362-bcd4-576fb279bf11.png)

**Comment by anshukrsingh** [comment]
Yea, it's working now., I think i forked from another old repository. Thanks
