### ISSUE TITLE
Search function

### ISSUE THREAD

**Issue by MajMcCloud** [albertobsd/keysubtracter#31]
Hey!

love your tools.
One idea would be to have a feature to search the subtracted keys file for a target publickey.
So after having the result with keyhunt, you can easily return the difference needed for calculation.

Thanks!
Warm regards
Florian

**Comment by albertobsd** [comment]
Well, sounds like a good idea, but if you hit something you can search or filter your input with the `grep` command

File:
```
023e40191ed19ba1c82d3948ffad7d11efc7352e8a071b09750fc0a62cba295f15 # - 10
02ad82cfd538d8f9a98ea7d2393a958962d3dd783456284353084ad74e459ca98c # + 10
029649575661e11d5c7c277d008c7a6d6a56c14824e31673a5a49809f94777858e # - 20
02a1c7e1fffa740388689234491047208e0f7c23a9bee61b61ef035a6d016a709c # + 20
02a3c299147e9cb77fc03b13712700361b6175e3fa3521a297854c73f680f8b389 # - 30
028a6ee5e557bf738107e02cf5533dd40d6390f4a4a1539092774246c1352583b8 # + 30
03911f949fe7d1c81152974161306cda43c810ec50839cee0ff1fd047b25eb95bf # - 40
0311d6b86415d2122e4103d63906cfda90f9f6359f2b90887839b25a2fe7e6de6b # + 40
02c234090ac778e0e311d4306a9ba41e042900f44f7166e3a17786e4376bfdfabf # - 50
039f147c6939d4d3b66eb7ae37f67652d1b4e28794a55ca39e22db6eb2c8949505 # + 50
02ceb6cbbcdbdf5ef7150682150f4ce2c6f4807b349827dcdbdd1f2efa885a2630 # target
```

Comnand

```
cat input.txt | grep 02ad82cfd538d8f9a98ea7d2393a958962d3dd783456284353084ad74e459ca98c
```

Output
```
02ad82cfd538d8f9a98ea7d2393a958962d3dd783456284353084ad74e459ca98c # + 10
```

Offset +10

Also any good text editor have a search function.

Is not my intention reinvent the wheel 

Regards

**Comment by MajMcCloud** [comment]
Thats nice. Thanks for the hint with grep.

Im just thinking, if you got lets say 1 Mrd of entries, thats a huge file, which is not that easy to read into a text editor (if memory is limited)...

But yeah, grep would be then the solution

Thanks!
