### ISSUE TITLE
compile error...ubuntu linux... any solution.?

### ISSUE THREAD

**Issue by sari777** [albertobsd/keysubtracter#34]
facing the error."
keygen.c: In function ‘main’:
keygen.c:152:66: warning: unknown conversion type character ‘\x0a’ in format [-Wformat=]
  152 |                                 fprintf(stderr,"OpenSSL error: %l\n",err);
      |                                                                  ^~
keygen.c:152:48: warning: too many arguments for format [-Wformat-extra-args]
  152 |                                 fprintf(stderr,"OpenSSL error: %l\n",err);
      |                                                ^~~~~~~~~~~~~~~~~~~~~
keygen.c:135:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-resul
]
  135 |                         fread(buffer_key,1,bytes,fd);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
keygen.c:145:25: warning: ignoring return value of ‘fread’ declared with attribute ‘warn_unused_result’ [-Wunused-resul
]
  145 |                         fread(buffer_key,1,bytes,fd);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
keygen.c:158:25: warning: ignoring return value of ‘getrandom’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  158 |                         getrandom(buffer_key,bytes,GRND_NONBLOCK);
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O3 -o sharedsecret sharedsecret.c gmpecc.c util.o sha256.o base58.o rmd160.o -lgmp `libgcrypt-config --cflags --libs`
sharedsecret.c: In function ‘main’:
sharedsecret.c:82:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   82 |         fgets(buffer,1022,stdin);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
sharedsecret.c:90:9: warning: ignoring return value of ‘fgets’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
   90 |         fgets(buffer,1022,stdin);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
gcc -o addr2rmd addr2rmd.c util.o base58.o
rm *.o
"

**Comment by albertobsd** [comment]
If you read carefully all the lines have "warning" and no "error".

The program is already compiled, just run it.

Regards!

**Comment by sari777** [comment]
ok dear..how to run it..what will be the command.

**Comment by sari777** [comment]
yes it is working dear..thanks for your support.good
