### ISSUE TITLE
can't open output file

### ISSUE THREAD

**Issue by Xh0st** [albertobsd/keysubtracter#4]
Hello, I have a problem. I'm using ubuntu terminal in windows10 after generating the subtractedkey with the command -o out.txt i can't access the file. You do not have permission to access the file, I have try to chmod 777 with no succes also when trying to delete the file with rm out.txt give me > rm: cannot remove 'out.txt': No such file or directory. I have try to change the output name and same issue. I have like 5 file output now with different name .. i can't acces them or delete them

**Comment by albertobsd** [comment]
how do you are opening the file?

BYW this is not related with the tool, this is a linux problem or some other issue, i can't help with this issue.
