### ISSUE TITLE
Hi Alberto , could you create -f address for ETH?

### ISSUE THREAD

**Issue by malcamal** [albertobsd/keysubtracter#40]

**Comment by albertobsd** [comment]
-m address -c eth -f file should work

**Comment by malcamal** [comment]
Hi Alberto
-m address  -c eth -f file does not work
________________________________

**Comment by albertobsd** [comment]
It should work, can you send a full screenshot?

**Comment by malcamal** [comment]
./keysubtracter -p 02ceb6cbbcdbdf5ef7150682150f4ce2c6f4807b349827dcdbdd1f2efa885a2630 -n 10 -b 120 -c eth -f address -x

________________________________
