### ISSUE TITLE
a little help please :) 

### ISSUE THREAD

**Issue by robywijaya007** [albertobsd/keysubtracter#8]
hello alberto ,
i tried to make compile but it was going error 
gcc -O3 -c gmpecc.c -o gmpecc.o
gcc -O3 -c util.c -o util.o
gcc -o keysubtracter keysubtracter.c gmpecc.o util.o -lgmp
/usr/bin/ld: gmpecc.o:(.bss+0x2020): multiple definition of `EC'; /tmp/ccmOxZkI.o:(.bss+0x0): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x0): multiple definition of `DoublingG'; /tmp/ccmOxZkI.o:(.bss+0x40): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x2000): multiple definition of `G'; /tmp/ccmOxZkI.o:(.bss+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:4: default] Error 1

please help 
Best regards

**Comment by albertobsd** [comment]
please add more details of your system, Linux version, Gcc Version.

**Comment by robywijaya007** [comment]
Dear Alberto,
Thank you for your kind reply ,  gcc version 10.2.0 running on  Ubuntu 20.10 groovy . 
Kind regards

**Comment by we-akri** [comment]
fatal error
```
gcc -O3 -c gmpecc.c -o gmpecc.o
gmpecc.c:1:10: fatal error: gmp.h: No such file or directory
 #include <gmp.h>
          ^~~~~~~
compilation terminated.
Makefile:2: recipe for target 'default' failed
make: *** [default] Error 1
```

gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by albertobsd** [comment]
@we-akri install  libgmpdev

**Comment by we-akri** [comment]
Thank you
