### ISSUE TITLE
Does keysubtracter use vector addition subtraction or only simpe addition subtraction ?

### ISSUE THREAD

**Issue by Manosuper** [albertobsd/keysubtracter#9]
Hello. Big Thank you for your codes Friend !!!

Why reult of  key subtracter is diferent when in this, for example https://github.com/MrMaxweII/Secp256k1-Calculator calculator ?

In Yur example in keyhunt:

02d1e9e73f79c1c86eda6096987c13c7547f808f571910c3d50f0dfd94456e21f6 # + 407460253732
03a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f0edbee53de0d4 # target

First, why pubkey change them prfixe from "02" to "03" ?

And why the I add to pubkey in **calculator**, I get result:

02a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f0edbee53de0d4 + 407460253732 = a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f12e3345631806 !!!

and if I not remove 02, then:

02a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f0edbee53de0d4 +  407460253732 =

a2efa402fd5268400c77c20e574ba866949034211daee06d3a4c7119a4f69584 !!!

**So,

03a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f0edbee53de0d4 <> a2efa402fd5268400c77c20e574ba86409ededee7c4020e4b9f12e3345631806 <>  a2efa402fd5268400c77c20e574ba866949034211daee06d3a4c7119a4f69584

!**

Albrto, you key substracter is good idea. This method already tested, and worked. But, please, see you code, I think in code is some error, what if You remove error, this will be again Your's  helpfull   supercode ))

Br !!!

**Comment by albertobsd** [comment]
keysubtracter use Elliptic curve Addition.

02 y 03 are standar notation in  compress publickey.

Please read the next link almost two times: https://www.oreilly.com/library/view/mastering-bitcoin/9781491902639/ch04.html
